"""empty message

Revision ID: 202559c544a2
Revises: 
Create Date: 2023-11-21 23:44:59.988298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202559c544a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('login_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_email', sa.String(length=225), nullable=False),
    sa.Column('login_date', sa.DateTime(), nullable=True),
    sa.Column('logout_date', sa.DateTime(), nullable=True),
    sa.Column('login_userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['login_userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('login_id')
    )
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_login_date'), ['login_date'], unique=False)

    op.create_table('med_reminder',
    sa.Column('md_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('md_date', sa.DateTime(), nullable=True),
    sa.Column('md_alert', sa.String(length=50), nullable=False),
    sa.Column('md_detail', sa.Text(), nullable=True),
    sa.Column('md_userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['md_userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('md_id')
    )
    with op.batch_alter_table('med_reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_med_reminder_md_date'), ['md_date'], unique=False)

    op.create_table('med_track',
    sa.Column('mt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mt_date', sa.DateTime(), nullable=True),
    sa.Column('mt_track', sa.Boolean(), nullable=True),
    sa.Column('mt_userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mt_userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('mt_id')
    )
    with op.batch_alter_table('med_track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_med_track_mt_date'), ['mt_date'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_pass', sa.String(length=225), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_pass')

    with op.batch_alter_table('med_track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_med_track_mt_date'))

    op.drop_table('med_track')
    with op.batch_alter_table('med_reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_med_reminder_md_date'))

    op.drop_table('med_reminder')
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_login_date'))

    op.drop_table('login')
    # ### end Alembic commands ###
